---
# Created by hand so we have a "cluster dns" for:
#   alertmanager.monitoring.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: kube-prometheus-stack-alertmanager
  type: "ClusterIP"
