---
# Created by hand so we have a "cluster dns" for:
#   grafana.monitoring.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  type: "ClusterIP"
