---
# Created by hand so we have a "cluster dns" for:
#   prometheus.monitoring.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
  type: "ClusterIP"
