---
- name: "Uninstall helm package {{ prometheus_kube_state_metrics_helm_package_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ prometheus_kube_state_metrics_helm_package_name }}"
    namespace: "{{ prometheus_kube_state_metrics_namespace }}"
    state: absent
