---
- name: "Install helm package {{ prometheus_kube_state_metrics_helm_repo_name }}/{{ prometheus_kube_state_metrics_helm_package_name }} {{ prometheus_kube_state_metrics_helm_package_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ prometheus_kube_state_metrics_helm_package_name }}"
    chart_ref: "{{ prometheus_kube_state_metrics_helm_repo_name }}/{{ prometheus_kube_state_metrics_helm_package_name }}"
    namespace: "{{ prometheus_kube_state_metrics_namespace }}"
    chart_version: "{{ prometheus_kube_state_metrics_helm_version }}"
    create_namespace: "{{ prometheus_kube_state_metrics_create_namespace }}"
    state: present
    values:
      replicas: "{{ prometheus_kube_state_metrics_replicas }}"
      prometheus:
        monitor:
          enabled: true
      selfMonitor:
        enabled: "{{ prometheus_kube_state_metrics_self_monitor_enabled | bool }}"
      verticalPodAutoscaler:
        enabled: "{{ prometheus_kube_state_metrics_vertical_podautoscaler | bool }}"
      nodeSelector:
        kubernetes.io/os: linux
