---
- name: "Uninstall helm package {{ prometheus_node_exporter_helm_package_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ prometheus_node_exporter_helm_package_name }}"
    namespace: "{{ prometheus_node_exporter_namespace }}"
    state: absent
