---
cilium_helm_repo_name: cilium
cilium_helm_chart_name: cilium
cilium_helm_release_name: cilium

cilium_ensure: present
cilium_helm_version: 1.12.3
cilium_create_namespace: "yes"
cilium_namespace: kube-system
cilium_installation_values:
  cluster:
    name: dunedaq
  containerRuntime:
    integration: auto
  ipam:
    mode: kubernetes
  monitor:
    enabled: true
  logSystemLoad: true
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  ingressController:
    enabled: true
  hubble:
    enabled: true
    metrics:
      enabled: [dns, drop, flow, flows-to-world, icmp]
      serviceMonitor:
        enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
  l7Proxy: true
  tunnel: vxlan
  wellKnownIdentities:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  operator:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
