---
- name: "Uninstall helm package {{ cilium_helm_release_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ cilium_helm_release_name }}"
    namespace: "{{ cilium_namespace }}"
    state: absent
