---
- name: "Install {{ cilium_helm_release_name }} via helm"
  ansible.builtin.include_tasks: helm_install.yml
  when:
    - cilium_ensure == "present"
    - kind_cluster_disable_default_cni | default('true') | bool
