---
krew_download_if_missing: true
krew_install: true

krew_version: NULL
krew_binary_ensure: present

krew_binary_name: krew

krew_latest_version_url: https://api.github.com/repos/kubernetes-sigs/krew/releases/latest
krew_release_baseurl: https://github.com/kubernetes-sigs/krew/releases/download
krew_release_tailurl: "krew-{{ ansible_system | lower }}_{{ go_arch }}.tar.gz"

krew_home: "{{ '~' | expanduser }}/.krew"
