---
- name: "Find information about {{ cilium_helm_release_name }} via helm"
  kubernetes.core.helm_info:
    release_name: "{{ cilium_helm_release_name }}"
    release_namespace: "{{ cilium_namespace }}"
    release_state: deployed
  register: cilium_helm_info
  changed_when: false
  listen: prometheus installed

- name: "Enable {{ cilium_helm_release_name }} serviceMonitor via helm"
  ansible.builtin.command:
    argv:
      - "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
      - upgrade
      - "{{ cilium_helm_release_name }}"
      - "{{ cilium_helm_repo_name }}/{{ cilium_helm_chart_name }}"
      - --namespace
      - "{{ cilium_namespace }}"
      - --reuse-values
      - --version
      - "{{ cilium_helm_info.status.chart | replace(cilium_helm_release_name + '-','') }}"
      - --values
      - "{{ dune_daq_conf_path | expanduser }}/cilium/prometheus_systemmonitor.yml"
  listen: prometheus installed
