---
- name: "Install helm package {{ metrics_server_helm_repo_name }}/{{ metrics_server_helm_chart_name }} {{ metrics_server_helm_release_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ metrics_server_helm_release_name }}"
    chart_ref: "{{ metrics_server_helm_repo_name }}/{{ metrics_server_helm_chart_name }}"
    namespace: "{{ metrics_server_namespace }}"
    chart_version: "{{ metrics_server_helm_version }}"
    create_namespace: "{{ metrics_server_create_namespace }}"
    state: present
    values:
      metrics:
        enabled: true
      serviceMonitor:
        enabled: "{{ metrics_server_service_monitor_enabled | bool }}"
      serviceAccount:
        create: true
      replicas: "{{ metrics_server_replicas }}"
