---
- name: "Install helm package {{ prometheus_adapter_helm_repo_name }}/{{ prometheus_adapter_helm_chart_name }} {{ prometheus_adapter_helm_release_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ prometheus_adapter_helm_release_name }}"
    chart_ref: "{{ prometheus_adapter_helm_repo_name }}/{{ prometheus_adapter_helm_chart_name }}"
    namespace: "{{ prometheus_adapter_namespace }}"
    chart_version: "{{ prometheus_adapter_helm_version }}"
    create_namespace: "{{ prometheus_adapter_create_namespace }}"
    state: present
    values:
      replicas: "{{ prometheus_adapter_replicas }}"
      prometheus: "{{ prometheus_adapter_prometheus_settings }}"
      rules.resource: "{{ prometheus_adapter_rules_resource }}"
