---
- name: Make directory to store kube_stack_prometheus files
  ansible.builtin.file:
    path: "{{ dune_daq_conf_path | expanduser }}/kube_stack_prometheus"
    state: directory
    mode: "0755"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: "Install helm package {{ kube_stack_prometheus_helm_repo_name }}/{{ kube_stack_prometheus_helm_chart_name }} {{ kube_stack_prometheus_helm_release_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ kube_stack_prometheus_helm_release_name }}"
    chart_ref: "{{ kube_stack_prometheus_helm_repo_name }}/{{ kube_stack_prometheus_helm_chart_name }}"
    namespace: "{{ kube_stack_prometheus_namespace }}"
    chart_version: "{{ kube_stack_prometheus_helm_version }}"
    create_namespace: "{{ kube_stack_prometheus_create_namespace }}"
    state: present
    values:
      alertmanager:
        enabled: false
      grafana:
        enabled: false
        forceDeployDashboards: true
        sidecar:
          dashboards:
            enabled: true
            folderAnnotation: k8s-sidecar-target-directory
            provider:
              foldersFromFilesStructure: true
      prometheus:
        enabled: false

- name: set Pod Security Admission
  ansible.builtin.include_tasks: pod_security_admission.yml
  when:
    - kube_stack_prometheus_set_pod_security_admission | bool

- name: setup Pretty Services
  ansible.builtin.include_tasks: make_pretty_services.yml
  when:
    - kube_stack_prometheus_pretty_service_names | bool
