---
- name: Make directory to store kube_stack_prometheus files
  ansible.builtin.file:
    path: "{{ dune_daq_conf_path | expanduser }}/kube_stack_prometheus"
    state: directory
    mode: "0755"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: "Install helm package {{ kube_stack_prometheus_helm_repo_name }}/{{ kube_stack_prometheus_helm_chart_name }} {{ kube_stack_prometheus_helm_release_name }}"
  kubernetes.core.helm:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    name: "{{ kube_stack_prometheus_helm_release_name }}"
    chart_ref: "{{ kube_stack_prometheus_helm_repo_name }}/{{ kube_stack_prometheus_helm_chart_name }}"
    namespace: "{{ kube_stack_prometheus_namespace }}"
    chart_version: "{{ kube_stack_prometheus_helm_version }}"
    create_namespace: "{{ kube_stack_prometheus_create_namespace }}"
    state: present
    values:
      grafana:
        adminPassword: "{{ kube_stack_prometheus_grafana_password }}"
      prometheus:
        prometheusSpec:
          podMonitorSelectorNilUsesHelmValues: "{{ kube_stack_prometheus_podmonitor_selector_niluseshelmvalues }}"
          podMonitorSelector: "{{ kube_stack_prometheus_podmonitor_selector }}"
          podMonitorNamespaceSelector: "{{ kube_stack_prometheus_podmonitornamespace_selector }}"
          ruleSelectorNilUsesHelmValues: "{{ kube_stack_prometheus_rule_selector_niluseshelmvalues }}"
          ruleSelector: "{{ kube_stack_prometheus_rule_selector }}"
          ruleNamespaceSelector: "{{ kube_stack_prometheus_rulenamespace_selector }}"
          serviceMonitorSelectorNilUsesHelmValues: "{{ kube_stack_prometheus_servicemonitor_selector_niluseshelmvalues }}"
          serviceMonitorSelector: "{{ kube_stack_prometheus_servicemonitor_selector }}"
          serviceMonitorNamespaceSelector: "{{ kube_stack_prometheus_servicemonitornamespace_selector }}"
          probeSelectorNilUsesHelmValues: "{{ kube_stack_prometheus_probe_selector_niluseshelmvalues }}"
          probeSelector: "{{ kube_stack_prometheus_probe_selector }}"
          probeNamespaceSelector: "{{ kube_stack_prometheus_probenamespace_selector }}"
      alertmanager:
        alertmanagerSpec:
          alertmanagerConfigSelector: "{{ kube_stack_prometheus_alertmanagerconfig_selector }}"
          alertmanagerConfigNamespaceSelector: "{{ kube_stack_prometheus_alertmanagerconfignamespace_selector }}"
  notify: prometheus installed

- name: set Pod Security Admission
  ansible.builtin.include_tasks: pod_security_admission.yml
  when:
    - kube_stack_prometheus_set_pod_security_admission | bool

- name: setup Pretty Services
  ansible.builtin.include_tasks: make_pretty_services.yml
  when:
    - kube_stack_prometheus_pretty_service_names | bool
