---
- name: "Remove {{ dune_daq_bin_path }}/{{ kubelet_binary_name }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubelet_binary_name }}"
    state: absent

- name: "Remove {{ dune_daq_bin_path }}/{{ kubelet_ver_bin }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubelet_ver_bin }}"
    state: absent
  vars:
    kubelet_ver_bin: "{{ kubelet_binary_name }}-{{ kubelet_requested_version.stdout }}"
