---
# should this do something to PATH?
- name: "Link {{ dune_daq_bin_path }}/{{ kubectl_ver_bin }} to {{ dune_daq_bin_path }}/{{ kubectl_binary_name }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubectl_ver_bin }}"
    dest: "{{ dune_daq_bin_path | expanduser }}/{{ kubectl_binary_name }}"
    state: link
  vars:
    kubectl_ver_bin: "{{ kubectl_binary_name }}-{{ kubectl_requested_version.stdout }}"
  when:
    - kubectl_binary_ensure == "present"
    - kubectl_binary_make_version_link | bool
