---
# should this do something to PATH?
- name: "Link {{ dune_daq_bin_path }}/{{ kubeadm_ver_bin }} to {{ dune_daq_bin_path }}/{{ kubeadm_binary_name }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubeadm_ver_bin }}"
    dest: "{{ dune_daq_bin_path | expanduser }}/{{ kubeadm_binary_name }}"
    state: link
  vars:
    kubeadm_ver_bin: "{{ kubeadm_binary_name }}-{{ kubeadm_requested_version.stdout }}"
  when:
    - kubeadm_binary_ensure == "present"
    - kubeadm_binary_make_version_link | bool
