---
- name: "Remove {{ dune_daq_bin_path }}/{{ kubeadm_binary_name }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubeadm_binary_name }}"
    state: absent

- name: "Remove {{ dune_daq_bin_path }}/{{ kubeadm_ver_bin }}"
  ansible.builtin.file:
    src: "{{ dune_daq_bin_path | expanduser }}/{{ kubeadm_ver_bin }}"
    state: absent
  vars:
    kubeadm_ver_bin: "{{ kubeadm_binary_name }}-{{ kubeadm_requested_version.stdout }}"
