---
- name: "Install Helm {{ helm_plugin_monitor_name }} plugin"
  kubernetes.core.helm_plugin:
    binary_path: "{{ dune_daq_bin_path | expanduser }}/{{ helm_binary_name }}"
    plugin_path: "{{ helm_plugin_monitor_path }}"
    state: "{{ helm_plugin_monitor_state }}"
    plugin_version: "{{ helm_plugin_monitor_version }}"
