---
- name: "Install kubectl krew plugin {{ kubectl_krew_plugin_socks5_proxy_name }}"
  ansible.builtin.command:
    argv:
      - "{{ dune_daq_bin_path | expanduser }}/{{ kubectl_binary_name }}"
      - krew
      - install
      - "{{ kubectl_krew_plugin_socks5_proxy_name }}"
    creates: "{{ krew_home }}/bin/kubectl-socks5_proxy"
