---
- name: "Extract {{ krew_binary_name }}-{{ ansible_system | lower }}_{{ go_arch }} from {{ krew_home }}/archive/{{ krew_ver_bin }}.tar.gz"
  ansible.builtin.unarchive:
    src: "{{ krew_home }}/archive/{{ krew_ver_bin }}.tar.gz"
    dest: "{{ krew_home }}"
    creates: "{{ krew_binary_name }}-{{ ansible_system | lower }}_{{ go_arch }}"
    extra_opts: "./{{ krew_binary_name }}-{{ ansible_system | lower }}_{{ go_arch }}"
    remote_src: true
  vars:
    krew_ver_bin: "{{ krew_binary_name }}-{{ ansible_system | lower }}-{{ krew_requested_version.stdout }}"

- name: Run krew installer
  ansible.builtin.command:
    argv:
      - "{{ krew_home }}/{{ krew_ver_bin }}"
      - install
      - krew
    creates: "{{ krew_home }}/bin/kubectl-krew"
  vars:
    krew_ver_bin: "{{ krew_binary_name }}-{{ ansible_system | lower }}_{{ go_arch }}"

- name: "Put {{ krew_home }}/bin in PATH for bash"
  ansible.builtin.copy:
    content: "export PATH=${PATH}:{{ krew_home }}/bin"
    dest: "{{ '~' | expanduser }}/.bashrc.d/add_krew_bin_path.bashrc"
    mode: "0600"
